module.exports={
    baseUrl:"/",
    devServer:{
        host:"127.0.0.1",
        port:8080,
        proxy:{
        '/':{
            target:"http://localhost:3000",
            changeOrigin:true,
            ws:true,
            pathRewrite:{
                "^/":''
            }
        }
    }
  }
}